apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: self-crt
spec:
  secretName: my-selfsigned-cert
  commonName: "my-selfsigned-root-ca"
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer